# Generated by Django 4.1.7 on 2025-02-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccionambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.CharField(default='Laboratorio A', max_length=50)),
                ('equipo_computo', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
                ('proyector_multimedia', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
                ('red', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
                ('fluido_electrico', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
                ('orden_limpieza', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
                ('modulos', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
            ],
        ),
    ]
