# Generated by Django 5.1.6 on 2025-02-10 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_control', '0002_delete_inspeccionambientes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccionambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=50)),
                ('equipo_computo', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
                ('proyector_multimedia', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
                ('red', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
                ('fluido_electrico', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
                ('orden_limpieza', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
                ('modulos', models.CharField(choices=[('C', 'Correcto'), ('O', 'Observación')], max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
